In [3]:
import pandas as pd
import numpy as np

In [7]:
df1 = pd.read_csv('./UCD_Orders_New_3.csv', low_memory=False)

In [8]:
df1.head()

,Unnamed: 0,Order_ID,Market_ID,OrQuickNote,OrRefID,OrCancelled,OrShipPolicy,Customer_ID,OrCuTiID,OrCuFirstName,...,PyParentPyID,PyScID,PyAcquirerRefNum,PyMethodEntrySource,PyIsChargeback,PyProcessorSettlementCode,PyAuthenticationCode,ingest_timestamp_y,event_date_y,count
0,0,3070781814,368,NaN,NaN,False,False,3886031494,NaN,Cornelia,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2021-07-26 11:03:07.63267 UTC,2021-07-26,1671
1,1,3070781814,368,NaN,NaN,False,False,3886031494,NaN,Cornelia,...,NaN,NaN,NaN,1.0,False,NaN,NaN,2021-07-26 11:03:07.63267 UTC,2021-07-26,1671
2,2,3072577004,368,NaN,OST,True,False,3880986614,NaN,Melanie,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2021-07-26 11:03:07.63267 UTC,2021-07-26,1671
3,3,3071982114,368,NaN,OST,False,False,3879233824,NaN,Ulrike,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2021-07-26 11:03:07.63267 UTC,2021-07-26,1671
4,4,2633440598,368,Vorkasse order placed on hold until payment is...,AWINDE320207,False,False,5088315058,NaN,Eleni,...,NaN,NaN,NaN,NaN,False,NaN,NaN,2021-07-26 11:03:07.63267 UTC,2021-07-26,321